services:
  - type: web
    name: ameba-ts         # <- rename avoids collision with existing service
    env: docker
    plan: free
    rootDir: .
    autoDeploy: true
    healthCheckPath: "/"
    envVars:
      - key: NODE_VERSION
        value: "20"

